### ISSUE TITLE
Missing binded for the "get_out_edges_of_idx" method in UndirectedMultigraph

### ISSUE THREAD

**Issue by charlesmurphy1** [antoineallard/base_graph#4]
I was using the basegraph module in python and its seems there is an issue with the binding. After defining a `basegraph.core.UndirectedMultigraph`, the method `get_out_edges_of_idx` is unusable seen the type of the output `List[BaseGraph::LabeledNeighbour]` has not been binded.

**Comment by SILIZ4** [comment]
Commit fa7d34e should fix it although it's not the easiest format to work with. You can access the different value of the adjacency using the dot operator:
```python
for neighbour in graph.get_out_edges_of_idx(0):
    print(neighbour.vertex_index, neighbour.label)
```
