### ISSUE TITLE
Invalid entries in adjacency matrix of UndirectedMutligraph

### ISSUE THREAD

**Issue by charlesmurphy1** [antoineallard/base_graph#5]
When using the `get_adjacency_matrix` method to extract the adjacency matrix of a `basepgrah.code.UndirectedMultigraph`, the entry a_{ij} of an edge with multiplicity greater than 1 is still equal to 1. This might be the intended behavior, but I was expected the entries of the outputed adjacency matrix to be equal to the edge multiplicities.

**Comment by SILIZ4** [comment]
It's an oversight of implementation, I'm going to fix this very soon

**Comment by SILIZ4** [comment]
Commit d280f28 fixes it.
